#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ducaun.dal
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ducaun")]
	public partial class fodeuDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertatendimento(atendimento instance);
    partial void Updateatendimento(atendimento instance);
    partial void Deleteatendimento(atendimento instance);
    partial void Insertcliente(cliente instance);
    partial void Updatecliente(cliente instance);
    partial void Deletecliente(cliente instance);
    partial void Insertfornecedore(fornecedore instance);
    partial void Updatefornecedore(fornecedore instance);
    partial void Deletefornecedore(fornecedore instance);
    partial void Insertfuncionario(funcionario instance);
    partial void Updatefuncionario(funcionario instance);
    partial void Deletefuncionario(funcionario instance);
    partial void Insertiten(iten instance);
    partial void Updateiten(iten instance);
    partial void Deleteiten(iten instance);
    partial void Insertprocedimento(procedimento instance);
    partial void Updateprocedimento(procedimento instance);
    partial void Deleteprocedimento(procedimento instance);
    partial void Insertproduto(produto instance);
    partial void Updateproduto(produto instance);
    partial void Deleteproduto(produto instance);
    partial void Insertvenda(venda instance);
    partial void Updatevenda(venda instance);
    partial void Deletevenda(venda instance);
    #endregion
		
		public fodeuDataContext() : 
				base(global::ducaun.dal.Properties.Settings.Default.ducaunConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public fodeuDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public fodeuDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public fodeuDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public fodeuDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<atendimento> atendimentos
		{
			get
			{
				return this.GetTable<atendimento>();
			}
		}
		
		public System.Data.Linq.Table<cliente> clientes
		{
			get
			{
				return this.GetTable<cliente>();
			}
		}
		
		public System.Data.Linq.Table<fornecedore> fornecedores
		{
			get
			{
				return this.GetTable<fornecedore>();
			}
		}
		
		public System.Data.Linq.Table<funcionario> funcionarios
		{
			get
			{
				return this.GetTable<funcionario>();
			}
		}
		
		public System.Data.Linq.Table<iten> itens
		{
			get
			{
				return this.GetTable<iten>();
			}
		}
		
		public System.Data.Linq.Table<procedimento> procedimentos
		{
			get
			{
				return this.GetTable<procedimento>();
			}
		}
		
		public System.Data.Linq.Table<produto> produtos
		{
			get
			{
				return this.GetTable<produto>();
			}
		}
		
		public System.Data.Linq.Table<usuario> usuarios
		{
			get
			{
				return this.GetTable<usuario>();
			}
		}
		
		public System.Data.Linq.Table<venda> vendas
		{
			get
			{
				return this.GetTable<venda>();
			}
		}
		
		public System.Data.Linq.Table<cidade> cidades
		{
			get
			{
				return this.GetTable<cidade>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.atendimentos")]
	public partial class atendimento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cod_atendimento;
		
		private string _data_atendimento;
		
		private System.Nullable<int> _cod_cliente;
		
		private System.Nullable<int> _cod_funcionario;
		
		private string _observacoes;
		
		private System.Nullable<int> _cod_procedimento;
		
		private EntityRef<cliente> _cliente;
		
		private EntityRef<funcionario> _funcionario;
		
		private EntityRef<procedimento> _procedimento;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncod_atendimentoChanging(int value);
    partial void Oncod_atendimentoChanged();
    partial void Ondata_atendimentoChanging(string value);
    partial void Ondata_atendimentoChanged();
    partial void Oncod_clienteChanging(System.Nullable<int> value);
    partial void Oncod_clienteChanged();
    partial void Oncod_funcionarioChanging(System.Nullable<int> value);
    partial void Oncod_funcionarioChanged();
    partial void OnobservacoesChanging(string value);
    partial void OnobservacoesChanged();
    partial void Oncod_procedimentoChanging(System.Nullable<int> value);
    partial void Oncod_procedimentoChanged();
    #endregion
		
		public atendimento()
		{
			this._cliente = default(EntityRef<cliente>);
			this._funcionario = default(EntityRef<funcionario>);
			this._procedimento = default(EntityRef<procedimento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_atendimento", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int cod_atendimento
		{
			get
			{
				return this._cod_atendimento;
			}
			set
			{
				if ((this._cod_atendimento != value))
				{
					if (this._procedimento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncod_atendimentoChanging(value);
					this.SendPropertyChanging();
					this._cod_atendimento = value;
					this.SendPropertyChanged("cod_atendimento");
					this.Oncod_atendimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_atendimento", DbType="VarChar(20)")]
		public string data_atendimento
		{
			get
			{
				return this._data_atendimento;
			}
			set
			{
				if ((this._data_atendimento != value))
				{
					this.Ondata_atendimentoChanging(value);
					this.SendPropertyChanging();
					this._data_atendimento = value;
					this.SendPropertyChanged("data_atendimento");
					this.Ondata_atendimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_cliente", DbType="Int")]
		public System.Nullable<int> cod_cliente
		{
			get
			{
				return this._cod_cliente;
			}
			set
			{
				if ((this._cod_cliente != value))
				{
					if (this._cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncod_clienteChanging(value);
					this.SendPropertyChanging();
					this._cod_cliente = value;
					this.SendPropertyChanged("cod_cliente");
					this.Oncod_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_funcionario", DbType="Int")]
		public System.Nullable<int> cod_funcionario
		{
			get
			{
				return this._cod_funcionario;
			}
			set
			{
				if ((this._cod_funcionario != value))
				{
					if (this._funcionario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncod_funcionarioChanging(value);
					this.SendPropertyChanging();
					this._cod_funcionario = value;
					this.SendPropertyChanged("cod_funcionario");
					this.Oncod_funcionarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observacoes", DbType="NChar(1000)")]
		public string observacoes
		{
			get
			{
				return this._observacoes;
			}
			set
			{
				if ((this._observacoes != value))
				{
					this.OnobservacoesChanging(value);
					this.SendPropertyChanging();
					this._observacoes = value;
					this.SendPropertyChanged("observacoes");
					this.OnobservacoesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_procedimento", DbType="Int")]
		public System.Nullable<int> cod_procedimento
		{
			get
			{
				return this._cod_procedimento;
			}
			set
			{
				if ((this._cod_procedimento != value))
				{
					this.Oncod_procedimentoChanging(value);
					this.SendPropertyChanging();
					this._cod_procedimento = value;
					this.SendPropertyChanged("cod_procedimento");
					this.Oncod_procedimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_atendimento", Storage="_cliente", ThisKey="cod_cliente", OtherKey="cod_cliente", IsForeignKey=true)]
		public cliente cliente
		{
			get
			{
				return this._cliente.Entity;
			}
			set
			{
				cliente previousValue = this._cliente.Entity;
				if (((previousValue != value) 
							|| (this._cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._cliente.Entity = null;
						previousValue.atendimentos.Remove(this);
					}
					this._cliente.Entity = value;
					if ((value != null))
					{
						value.atendimentos.Add(this);
						this._cod_cliente = value.cod_cliente;
					}
					else
					{
						this._cod_cliente = default(Nullable<int>);
					}
					this.SendPropertyChanged("cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="funcionario_atendimento", Storage="_funcionario", ThisKey="cod_funcionario", OtherKey="cod_funcionario", IsForeignKey=true)]
		public funcionario funcionario
		{
			get
			{
				return this._funcionario.Entity;
			}
			set
			{
				funcionario previousValue = this._funcionario.Entity;
				if (((previousValue != value) 
							|| (this._funcionario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._funcionario.Entity = null;
						previousValue.atendimentos.Remove(this);
					}
					this._funcionario.Entity = value;
					if ((value != null))
					{
						value.atendimentos.Add(this);
						this._cod_funcionario = value.cod_funcionario;
					}
					else
					{
						this._cod_funcionario = default(Nullable<int>);
					}
					this.SendPropertyChanged("funcionario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="procedimento_atendimento", Storage="_procedimento", ThisKey="cod_atendimento", OtherKey="cod_procedimento", IsForeignKey=true)]
		public procedimento procedimento
		{
			get
			{
				return this._procedimento.Entity;
			}
			set
			{
				procedimento previousValue = this._procedimento.Entity;
				if (((previousValue != value) 
							|| (this._procedimento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._procedimento.Entity = null;
						previousValue.atendimento = null;
					}
					this._procedimento.Entity = value;
					if ((value != null))
					{
						value.atendimento = this;
						this._cod_atendimento = value.cod_procedimento;
					}
					else
					{
						this._cod_atendimento = default(int);
					}
					this.SendPropertyChanged("procedimento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.clientes")]
	public partial class cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cod_cliente;
		
		private string _n_cliente;
		
		private string _endereco;
		
		private string _bairro;
		
		private string _cidade;
		
		private string _telefone;
		
		private string _celular;
		
		private string _cep;
		
		private string _obs;
		
		private string _cpf;
		
		private string _email;
		
		private string _data_nas;
		
		private string _numero;
		
		private EntitySet<atendimento> _atendimentos;
		
		private EntitySet<venda> _vendas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncod_clienteChanging(int value);
    partial void Oncod_clienteChanged();
    partial void Onn_clienteChanging(string value);
    partial void Onn_clienteChanged();
    partial void OnenderecoChanging(string value);
    partial void OnenderecoChanged();
    partial void OnbairroChanging(string value);
    partial void OnbairroChanged();
    partial void OncidadeChanging(string value);
    partial void OncidadeChanged();
    partial void OntelefoneChanging(string value);
    partial void OntelefoneChanged();
    partial void OncelularChanging(string value);
    partial void OncelularChanged();
    partial void OncepChanging(string value);
    partial void OncepChanged();
    partial void OnobsChanging(string value);
    partial void OnobsChanged();
    partial void OncpfChanging(string value);
    partial void OncpfChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Ondata_nasChanging(string value);
    partial void Ondata_nasChanged();
    partial void OnnumeroChanging(string value);
    partial void OnnumeroChanged();
    #endregion
		
		public cliente()
		{
			this._atendimentos = new EntitySet<atendimento>(new Action<atendimento>(this.attach_atendimentos), new Action<atendimento>(this.detach_atendimentos));
			this._vendas = new EntitySet<venda>(new Action<venda>(this.attach_vendas), new Action<venda>(this.detach_vendas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_cliente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int cod_cliente
		{
			get
			{
				return this._cod_cliente;
			}
			set
			{
				if ((this._cod_cliente != value))
				{
					this.Oncod_clienteChanging(value);
					this.SendPropertyChanging();
					this._cod_cliente = value;
					this.SendPropertyChanged("cod_cliente");
					this.Oncod_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_n_cliente", DbType="VarChar(30)")]
		public string n_cliente
		{
			get
			{
				return this._n_cliente;
			}
			set
			{
				if ((this._n_cliente != value))
				{
					this.Onn_clienteChanging(value);
					this.SendPropertyChanging();
					this._n_cliente = value;
					this.SendPropertyChanged("n_cliente");
					this.Onn_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endereco", DbType="VarChar(40)")]
		public string endereco
		{
			get
			{
				return this._endereco;
			}
			set
			{
				if ((this._endereco != value))
				{
					this.OnenderecoChanging(value);
					this.SendPropertyChanging();
					this._endereco = value;
					this.SendPropertyChanged("endereco");
					this.OnenderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bairro", DbType="VarChar(20)")]
		public string bairro
		{
			get
			{
				return this._bairro;
			}
			set
			{
				if ((this._bairro != value))
				{
					this.OnbairroChanging(value);
					this.SendPropertyChanging();
					this._bairro = value;
					this.SendPropertyChanged("bairro");
					this.OnbairroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidade", DbType="VarChar(20)")]
		public string cidade
		{
			get
			{
				return this._cidade;
			}
			set
			{
				if ((this._cidade != value))
				{
					this.OncidadeChanging(value);
					this.SendPropertyChanging();
					this._cidade = value;
					this.SendPropertyChanged("cidade");
					this.OncidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefone", DbType="VarChar(20)")]
		public string telefone
		{
			get
			{
				return this._telefone;
			}
			set
			{
				if ((this._telefone != value))
				{
					this.OntelefoneChanging(value);
					this.SendPropertyChanging();
					this._telefone = value;
					this.SendPropertyChanged("telefone");
					this.OntelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_celular", DbType="VarChar(20)")]
		public string celular
		{
			get
			{
				return this._celular;
			}
			set
			{
				if ((this._celular != value))
				{
					this.OncelularChanging(value);
					this.SendPropertyChanging();
					this._celular = value;
					this.SendPropertyChanged("celular");
					this.OncelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cep", DbType="VarChar(20)")]
		public string cep
		{
			get
			{
				return this._cep;
			}
			set
			{
				if ((this._cep != value))
				{
					this.OncepChanging(value);
					this.SendPropertyChanging();
					this._cep = value;
					this.SendPropertyChanged("cep");
					this.OncepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_obs", DbType="VarChar(1000)")]
		public string obs
		{
			get
			{
				return this._obs;
			}
			set
			{
				if ((this._obs != value))
				{
					this.OnobsChanging(value);
					this.SendPropertyChanging();
					this._obs = value;
					this.SendPropertyChanged("obs");
					this.OnobsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cpf", DbType="VarChar(20)")]
		public string cpf
		{
			get
			{
				return this._cpf;
			}
			set
			{
				if ((this._cpf != value))
				{
					this.OncpfChanging(value);
					this.SendPropertyChanging();
					this._cpf = value;
					this.SendPropertyChanged("cpf");
					this.OncpfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(80)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_nas", DbType="VarChar(20)")]
		public string data_nas
		{
			get
			{
				return this._data_nas;
			}
			set
			{
				if ((this._data_nas != value))
				{
					this.Ondata_nasChanging(value);
					this.SendPropertyChanging();
					this._data_nas = value;
					this.SendPropertyChanged("data_nas");
					this.Ondata_nasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero", DbType="VarChar(50)")]
		public string numero
		{
			get
			{
				return this._numero;
			}
			set
			{
				if ((this._numero != value))
				{
					this.OnnumeroChanging(value);
					this.SendPropertyChanging();
					this._numero = value;
					this.SendPropertyChanged("numero");
					this.OnnumeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_atendimento", Storage="_atendimentos", ThisKey="cod_cliente", OtherKey="cod_cliente")]
		public EntitySet<atendimento> atendimentos
		{
			get
			{
				return this._atendimentos;
			}
			set
			{
				this._atendimentos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_venda", Storage="_vendas", ThisKey="cod_cliente", OtherKey="cod_cliente")]
		public EntitySet<venda> vendas
		{
			get
			{
				return this._vendas;
			}
			set
			{
				this._vendas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_atendimentos(atendimento entity)
		{
			this.SendPropertyChanging();
			entity.cliente = this;
		}
		
		private void detach_atendimentos(atendimento entity)
		{
			this.SendPropertyChanging();
			entity.cliente = null;
		}
		
		private void attach_vendas(venda entity)
		{
			this.SendPropertyChanging();
			entity.cliente = this;
		}
		
		private void detach_vendas(venda entity)
		{
			this.SendPropertyChanging();
			entity.cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.fornecedores")]
	public partial class fornecedore : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cod_fornecedor;
		
		private string _razão;
		
		private string _fantasia;
		
		private string _endereco;
		
		private string _bairro;
		
		private string _cidade;
		
		private string _telefone;
		
		private string _celular;
		
		private string _cep;
		
		private string _obs;
		
		private string _cnpj;
		
		private string _cpf;
		
		private string _email;
		
		private EntitySet<produto> _produtos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncod_fornecedorChanging(int value);
    partial void Oncod_fornecedorChanged();
    partial void OnrazãoChanging(string value);
    partial void OnrazãoChanged();
    partial void OnfantasiaChanging(string value);
    partial void OnfantasiaChanged();
    partial void OnenderecoChanging(string value);
    partial void OnenderecoChanged();
    partial void OnbairroChanging(string value);
    partial void OnbairroChanged();
    partial void OncidadeChanging(string value);
    partial void OncidadeChanged();
    partial void OntelefoneChanging(string value);
    partial void OntelefoneChanged();
    partial void OncelularChanging(string value);
    partial void OncelularChanged();
    partial void OncepChanging(string value);
    partial void OncepChanged();
    partial void OnobsChanging(string value);
    partial void OnobsChanged();
    partial void OncnpjChanging(string value);
    partial void OncnpjChanged();
    partial void OncpfChanging(string value);
    partial void OncpfChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public fornecedore()
		{
			this._produtos = new EntitySet<produto>(new Action<produto>(this.attach_produtos), new Action<produto>(this.detach_produtos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_fornecedor", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int cod_fornecedor
		{
			get
			{
				return this._cod_fornecedor;
			}
			set
			{
				if ((this._cod_fornecedor != value))
				{
					this.Oncod_fornecedorChanging(value);
					this.SendPropertyChanging();
					this._cod_fornecedor = value;
					this.SendPropertyChanged("cod_fornecedor");
					this.Oncod_fornecedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_razão", DbType="VarChar(30)")]
		public string razão
		{
			get
			{
				return this._razão;
			}
			set
			{
				if ((this._razão != value))
				{
					this.OnrazãoChanging(value);
					this.SendPropertyChanging();
					this._razão = value;
					this.SendPropertyChanged("razão");
					this.OnrazãoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fantasia", DbType="VarChar(30)")]
		public string fantasia
		{
			get
			{
				return this._fantasia;
			}
			set
			{
				if ((this._fantasia != value))
				{
					this.OnfantasiaChanging(value);
					this.SendPropertyChanging();
					this._fantasia = value;
					this.SendPropertyChanged("fantasia");
					this.OnfantasiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endereco", DbType="VarChar(40)")]
		public string endereco
		{
			get
			{
				return this._endereco;
			}
			set
			{
				if ((this._endereco != value))
				{
					this.OnenderecoChanging(value);
					this.SendPropertyChanging();
					this._endereco = value;
					this.SendPropertyChanged("endereco");
					this.OnenderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bairro", DbType="VarChar(20)")]
		public string bairro
		{
			get
			{
				return this._bairro;
			}
			set
			{
				if ((this._bairro != value))
				{
					this.OnbairroChanging(value);
					this.SendPropertyChanging();
					this._bairro = value;
					this.SendPropertyChanged("bairro");
					this.OnbairroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidade", DbType="VarChar(20)")]
		public string cidade
		{
			get
			{
				return this._cidade;
			}
			set
			{
				if ((this._cidade != value))
				{
					this.OncidadeChanging(value);
					this.SendPropertyChanging();
					this._cidade = value;
					this.SendPropertyChanged("cidade");
					this.OncidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefone", DbType="VarChar(10)")]
		public string telefone
		{
			get
			{
				return this._telefone;
			}
			set
			{
				if ((this._telefone != value))
				{
					this.OntelefoneChanging(value);
					this.SendPropertyChanging();
					this._telefone = value;
					this.SendPropertyChanged("telefone");
					this.OntelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_celular", DbType="VarChar(10)")]
		public string celular
		{
			get
			{
				return this._celular;
			}
			set
			{
				if ((this._celular != value))
				{
					this.OncelularChanging(value);
					this.SendPropertyChanging();
					this._celular = value;
					this.SendPropertyChanged("celular");
					this.OncelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cep", DbType="VarChar(8)")]
		public string cep
		{
			get
			{
				return this._cep;
			}
			set
			{
				if ((this._cep != value))
				{
					this.OncepChanging(value);
					this.SendPropertyChanging();
					this._cep = value;
					this.SendPropertyChanged("cep");
					this.OncepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_obs", DbType="VarChar(1000)")]
		public string obs
		{
			get
			{
				return this._obs;
			}
			set
			{
				if ((this._obs != value))
				{
					this.OnobsChanging(value);
					this.SendPropertyChanging();
					this._obs = value;
					this.SendPropertyChanged("obs");
					this.OnobsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnpj", DbType="VarChar(20)")]
		public string cnpj
		{
			get
			{
				return this._cnpj;
			}
			set
			{
				if ((this._cnpj != value))
				{
					this.OncnpjChanging(value);
					this.SendPropertyChanging();
					this._cnpj = value;
					this.SendPropertyChanged("cnpj");
					this.OncnpjChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cpf", DbType="VarChar(20)")]
		public string cpf
		{
			get
			{
				return this._cpf;
			}
			set
			{
				if ((this._cpf != value))
				{
					this.OncpfChanging(value);
					this.SendPropertyChanging();
					this._cpf = value;
					this.SendPropertyChanged("cpf");
					this.OncpfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(80)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="fornecedore_produto", Storage="_produtos", ThisKey="cod_fornecedor", OtherKey="cod_fornecedor")]
		public EntitySet<produto> produtos
		{
			get
			{
				return this._produtos;
			}
			set
			{
				this._produtos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_produtos(produto entity)
		{
			this.SendPropertyChanging();
			entity.fornecedore = this;
		}
		
		private void detach_produtos(produto entity)
		{
			this.SendPropertyChanging();
			entity.fornecedore = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.funcionarios")]
	public partial class funcionario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cod_funcionario;
		
		private string _n_funcionario;
		
		private string _endereco;
		
		private string _bairro;
		
		private string _cidade;
		
		private string _telefone;
		
		private string _celular;
		
		private string _cep;
		
		private string _data_contratacao;
		
		private string _obs;
		
		private string _ctps;
		
		private string _cnpj;
		
		private string _cpf;
		
		private string _email;
		
		private EntitySet<atendimento> _atendimentos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncod_funcionarioChanging(int value);
    partial void Oncod_funcionarioChanged();
    partial void Onn_funcionarioChanging(string value);
    partial void Onn_funcionarioChanged();
    partial void OnenderecoChanging(string value);
    partial void OnenderecoChanged();
    partial void OnbairroChanging(string value);
    partial void OnbairroChanged();
    partial void OncidadeChanging(string value);
    partial void OncidadeChanged();
    partial void OntelefoneChanging(string value);
    partial void OntelefoneChanged();
    partial void OncelularChanging(string value);
    partial void OncelularChanged();
    partial void OncepChanging(string value);
    partial void OncepChanged();
    partial void Ondata_contratacaoChanging(string value);
    partial void Ondata_contratacaoChanged();
    partial void OnobsChanging(string value);
    partial void OnobsChanged();
    partial void OnctpsChanging(string value);
    partial void OnctpsChanged();
    partial void OncnpjChanging(string value);
    partial void OncnpjChanged();
    partial void OncpfChanging(string value);
    partial void OncpfChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public funcionario()
		{
			this._atendimentos = new EntitySet<atendimento>(new Action<atendimento>(this.attach_atendimentos), new Action<atendimento>(this.detach_atendimentos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_funcionario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int cod_funcionario
		{
			get
			{
				return this._cod_funcionario;
			}
			set
			{
				if ((this._cod_funcionario != value))
				{
					this.Oncod_funcionarioChanging(value);
					this.SendPropertyChanging();
					this._cod_funcionario = value;
					this.SendPropertyChanged("cod_funcionario");
					this.Oncod_funcionarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_n_funcionario", DbType="VarChar(30)")]
		public string n_funcionario
		{
			get
			{
				return this._n_funcionario;
			}
			set
			{
				if ((this._n_funcionario != value))
				{
					this.Onn_funcionarioChanging(value);
					this.SendPropertyChanging();
					this._n_funcionario = value;
					this.SendPropertyChanged("n_funcionario");
					this.Onn_funcionarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endereco", DbType="VarChar(40)")]
		public string endereco
		{
			get
			{
				return this._endereco;
			}
			set
			{
				if ((this._endereco != value))
				{
					this.OnenderecoChanging(value);
					this.SendPropertyChanging();
					this._endereco = value;
					this.SendPropertyChanged("endereco");
					this.OnenderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bairro", DbType="VarChar(20)")]
		public string bairro
		{
			get
			{
				return this._bairro;
			}
			set
			{
				if ((this._bairro != value))
				{
					this.OnbairroChanging(value);
					this.SendPropertyChanging();
					this._bairro = value;
					this.SendPropertyChanged("bairro");
					this.OnbairroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidade", DbType="VarChar(20)")]
		public string cidade
		{
			get
			{
				return this._cidade;
			}
			set
			{
				if ((this._cidade != value))
				{
					this.OncidadeChanging(value);
					this.SendPropertyChanging();
					this._cidade = value;
					this.SendPropertyChanged("cidade");
					this.OncidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefone", DbType="VarChar(10)")]
		public string telefone
		{
			get
			{
				return this._telefone;
			}
			set
			{
				if ((this._telefone != value))
				{
					this.OntelefoneChanging(value);
					this.SendPropertyChanging();
					this._telefone = value;
					this.SendPropertyChanged("telefone");
					this.OntelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_celular", DbType="VarChar(10)")]
		public string celular
		{
			get
			{
				return this._celular;
			}
			set
			{
				if ((this._celular != value))
				{
					this.OncelularChanging(value);
					this.SendPropertyChanging();
					this._celular = value;
					this.SendPropertyChanged("celular");
					this.OncelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cep", DbType="VarChar(8)")]
		public string cep
		{
			get
			{
				return this._cep;
			}
			set
			{
				if ((this._cep != value))
				{
					this.OncepChanging(value);
					this.SendPropertyChanging();
					this._cep = value;
					this.SendPropertyChanged("cep");
					this.OncepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_contratacao", DbType="VarChar(20)")]
		public string data_contratacao
		{
			get
			{
				return this._data_contratacao;
			}
			set
			{
				if ((this._data_contratacao != value))
				{
					this.Ondata_contratacaoChanging(value);
					this.SendPropertyChanging();
					this._data_contratacao = value;
					this.SendPropertyChanged("data_contratacao");
					this.Ondata_contratacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_obs", DbType="VarChar(1000)")]
		public string obs
		{
			get
			{
				return this._obs;
			}
			set
			{
				if ((this._obs != value))
				{
					this.OnobsChanging(value);
					this.SendPropertyChanging();
					this._obs = value;
					this.SendPropertyChanged("obs");
					this.OnobsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ctps", DbType="VarChar(30)")]
		public string ctps
		{
			get
			{
				return this._ctps;
			}
			set
			{
				if ((this._ctps != value))
				{
					this.OnctpsChanging(value);
					this.SendPropertyChanging();
					this._ctps = value;
					this.SendPropertyChanged("ctps");
					this.OnctpsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnpj", DbType="VarChar(20)")]
		public string cnpj
		{
			get
			{
				return this._cnpj;
			}
			set
			{
				if ((this._cnpj != value))
				{
					this.OncnpjChanging(value);
					this.SendPropertyChanging();
					this._cnpj = value;
					this.SendPropertyChanged("cnpj");
					this.OncnpjChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cpf", DbType="VarChar(20)")]
		public string cpf
		{
			get
			{
				return this._cpf;
			}
			set
			{
				if ((this._cpf != value))
				{
					this.OncpfChanging(value);
					this.SendPropertyChanging();
					this._cpf = value;
					this.SendPropertyChanged("cpf");
					this.OncpfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(80)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="funcionario_atendimento", Storage="_atendimentos", ThisKey="cod_funcionario", OtherKey="cod_funcionario")]
		public EntitySet<atendimento> atendimentos
		{
			get
			{
				return this._atendimentos;
			}
			set
			{
				this._atendimentos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_atendimentos(atendimento entity)
		{
			this.SendPropertyChanging();
			entity.funcionario = this;
		}
		
		private void detach_atendimentos(atendimento entity)
		{
			this.SendPropertyChanging();
			entity.funcionario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.itens")]
	public partial class iten : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cod_venda;
		
		private int _nritem;
		
		private int _cod_produto;
		
		private decimal _qtvenda;
		
		private decimal _vlproduto;
		
		private EntityRef<iten> _iten2;
		
		private EntityRef<iten> _iten4;
		
		private EntityRef<iten> _iten1;
		
		private EntityRef<iten> _iten3;
		
		private EntityRef<produto> _produto;
		
		private EntityRef<venda> _venda;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncod_vendaChanging(int value);
    partial void Oncod_vendaChanged();
    partial void OnnritemChanging(int value);
    partial void OnnritemChanged();
    partial void Oncod_produtoChanging(int value);
    partial void Oncod_produtoChanged();
    partial void OnqtvendaChanging(decimal value);
    partial void OnqtvendaChanged();
    partial void OnvlprodutoChanging(decimal value);
    partial void OnvlprodutoChanged();
    #endregion
		
		public iten()
		{
			this._iten2 = default(EntityRef<iten>);
			this._iten4 = default(EntityRef<iten>);
			this._iten1 = default(EntityRef<iten>);
			this._iten3 = default(EntityRef<iten>);
			this._produto = default(EntityRef<produto>);
			this._venda = default(EntityRef<venda>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_venda", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int cod_venda
		{
			get
			{
				return this._cod_venda;
			}
			set
			{
				if ((this._cod_venda != value))
				{
					if (((this._iten1.HasLoadedOrAssignedValue || this._iten3.HasLoadedOrAssignedValue) 
								|| this._venda.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncod_vendaChanging(value);
					this.SendPropertyChanging();
					this._cod_venda = value;
					this.SendPropertyChanged("cod_venda");
					this.Oncod_vendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nritem", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int nritem
		{
			get
			{
				return this._nritem;
			}
			set
			{
				if ((this._nritem != value))
				{
					if ((this._iten1.HasLoadedOrAssignedValue || this._iten3.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnnritemChanging(value);
					this.SendPropertyChanging();
					this._nritem = value;
					this.SendPropertyChanged("nritem");
					this.OnnritemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_produto", DbType="Int NOT NULL")]
		public int cod_produto
		{
			get
			{
				return this._cod_produto;
			}
			set
			{
				if ((this._cod_produto != value))
				{
					if (this._produto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncod_produtoChanging(value);
					this.SendPropertyChanging();
					this._cod_produto = value;
					this.SendPropertyChanged("cod_produto");
					this.Oncod_produtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qtvenda", DbType="Decimal(16,2) NOT NULL")]
		public decimal qtvenda
		{
			get
			{
				return this._qtvenda;
			}
			set
			{
				if ((this._qtvenda != value))
				{
					this.OnqtvendaChanging(value);
					this.SendPropertyChanging();
					this._qtvenda = value;
					this.SendPropertyChanged("qtvenda");
					this.OnqtvendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vlproduto", DbType="Decimal(16,2) NOT NULL")]
		public decimal vlproduto
		{
			get
			{
				return this._vlproduto;
			}
			set
			{
				if ((this._vlproduto != value))
				{
					this.OnvlprodutoChanging(value);
					this.SendPropertyChanging();
					this._vlproduto = value;
					this.SendPropertyChanged("vlproduto");
					this.OnvlprodutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="iten_iten", Storage="_iten2", ThisKey="cod_venda,nritem", OtherKey="cod_venda,nritem", IsUnique=true, IsForeignKey=false)]
		public iten iten2
		{
			get
			{
				return this._iten2.Entity;
			}
			set
			{
				iten previousValue = this._iten2.Entity;
				if (((previousValue != value) 
							|| (this._iten2.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._iten2.Entity = null;
						previousValue.iten1 = null;
					}
					this._iten2.Entity = value;
					if ((value != null))
					{
						value.iten1 = this;
					}
					this.SendPropertyChanged("iten2");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="iten_iten1", Storage="_iten4", ThisKey="cod_venda,nritem", OtherKey="cod_venda,nritem", IsUnique=true, IsForeignKey=false)]
		public iten iten4
		{
			get
			{
				return this._iten4.Entity;
			}
			set
			{
				iten previousValue = this._iten4.Entity;
				if (((previousValue != value) 
							|| (this._iten4.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._iten4.Entity = null;
						previousValue.iten3 = null;
					}
					this._iten4.Entity = value;
					if ((value != null))
					{
						value.iten3 = this;
					}
					this.SendPropertyChanged("iten4");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="iten_iten", Storage="_iten1", ThisKey="cod_venda,nritem", OtherKey="cod_venda,nritem", IsForeignKey=true)]
		public iten iten1
		{
			get
			{
				return this._iten1.Entity;
			}
			set
			{
				iten previousValue = this._iten1.Entity;
				if (((previousValue != value) 
							|| (this._iten1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._iten1.Entity = null;
						previousValue.iten2 = null;
					}
					this._iten1.Entity = value;
					if ((value != null))
					{
						value.iten2 = this;
						this._cod_venda = value.cod_venda;
						this._nritem = value.nritem;
					}
					else
					{
						this._cod_venda = default(int);
						this._nritem = default(int);
					}
					this.SendPropertyChanged("iten1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="iten_iten1", Storage="_iten3", ThisKey="cod_venda,nritem", OtherKey="cod_venda,nritem", IsForeignKey=true)]
		public iten iten3
		{
			get
			{
				return this._iten3.Entity;
			}
			set
			{
				iten previousValue = this._iten3.Entity;
				if (((previousValue != value) 
							|| (this._iten3.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._iten3.Entity = null;
						previousValue.iten4 = null;
					}
					this._iten3.Entity = value;
					if ((value != null))
					{
						value.iten4 = this;
						this._cod_venda = value.cod_venda;
						this._nritem = value.nritem;
					}
					else
					{
						this._cod_venda = default(int);
						this._nritem = default(int);
					}
					this.SendPropertyChanged("iten3");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="produto_iten", Storage="_produto", ThisKey="cod_produto", OtherKey="cod_produto", IsForeignKey=true)]
		public produto produto
		{
			get
			{
				return this._produto.Entity;
			}
			set
			{
				produto previousValue = this._produto.Entity;
				if (((previousValue != value) 
							|| (this._produto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._produto.Entity = null;
						previousValue.itens.Remove(this);
					}
					this._produto.Entity = value;
					if ((value != null))
					{
						value.itens.Add(this);
						this._cod_produto = value.cod_produto;
					}
					else
					{
						this._cod_produto = default(int);
					}
					this.SendPropertyChanged("produto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="venda_iten", Storage="_venda", ThisKey="cod_venda", OtherKey="cod_venda", IsForeignKey=true)]
		public venda venda
		{
			get
			{
				return this._venda.Entity;
			}
			set
			{
				venda previousValue = this._venda.Entity;
				if (((previousValue != value) 
							|| (this._venda.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._venda.Entity = null;
						previousValue.itens.Remove(this);
					}
					this._venda.Entity = value;
					if ((value != null))
					{
						value.itens.Add(this);
						this._cod_venda = value.cod_venda;
					}
					else
					{
						this._cod_venda = default(int);
					}
					this.SendPropertyChanged("venda");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.procedimentos")]
	public partial class procedimento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cod_procedimento;
		
		private string _des_procedimento;
		
		private EntityRef<atendimento> _atendimento;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncod_procedimentoChanging(int value);
    partial void Oncod_procedimentoChanged();
    partial void Ondes_procedimentoChanging(string value);
    partial void Ondes_procedimentoChanged();
    #endregion
		
		public procedimento()
		{
			this._atendimento = default(EntityRef<atendimento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_procedimento", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int cod_procedimento
		{
			get
			{
				return this._cod_procedimento;
			}
			set
			{
				if ((this._cod_procedimento != value))
				{
					this.Oncod_procedimentoChanging(value);
					this.SendPropertyChanging();
					this._cod_procedimento = value;
					this.SendPropertyChanged("cod_procedimento");
					this.Oncod_procedimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_des_procedimento", DbType="VarChar(30)")]
		public string des_procedimento
		{
			get
			{
				return this._des_procedimento;
			}
			set
			{
				if ((this._des_procedimento != value))
				{
					this.Ondes_procedimentoChanging(value);
					this.SendPropertyChanging();
					this._des_procedimento = value;
					this.SendPropertyChanged("des_procedimento");
					this.Ondes_procedimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="procedimento_atendimento", Storage="_atendimento", ThisKey="cod_procedimento", OtherKey="cod_atendimento", IsUnique=true, IsForeignKey=false)]
		public atendimento atendimento
		{
			get
			{
				return this._atendimento.Entity;
			}
			set
			{
				atendimento previousValue = this._atendimento.Entity;
				if (((previousValue != value) 
							|| (this._atendimento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._atendimento.Entity = null;
						previousValue.procedimento = null;
					}
					this._atendimento.Entity = value;
					if ((value != null))
					{
						value.procedimento = this;
					}
					this.SendPropertyChanged("atendimento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.produtos")]
	public partial class produto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cod_produto;
		
		private string _des_produto;
		
		private string _ean;
		
		private System.Nullable<int> _cod_fornecedor;
		
		private System.Nullable<decimal> _vl_produto;
		
		private System.Nullable<float> _est_produto;
		
		private string _un_medida;
		
		private string _desc_reduzida;
		
		private System.Nullable<decimal> _margem;
		
		private System.Nullable<decimal> _custo;
		
		private EntitySet<iten> _itens;
		
		private EntityRef<fornecedore> _fornecedore;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncod_produtoChanging(int value);
    partial void Oncod_produtoChanged();
    partial void Ondes_produtoChanging(string value);
    partial void Ondes_produtoChanged();
    partial void OneanChanging(string value);
    partial void OneanChanged();
    partial void Oncod_fornecedorChanging(System.Nullable<int> value);
    partial void Oncod_fornecedorChanged();
    partial void Onvl_produtoChanging(System.Nullable<decimal> value);
    partial void Onvl_produtoChanged();
    partial void Onest_produtoChanging(System.Nullable<float> value);
    partial void Onest_produtoChanged();
    partial void Onun_medidaChanging(string value);
    partial void Onun_medidaChanged();
    partial void Ondesc_reduzidaChanging(string value);
    partial void Ondesc_reduzidaChanged();
    partial void OnmargemChanging(System.Nullable<decimal> value);
    partial void OnmargemChanged();
    partial void OncustoChanging(System.Nullable<decimal> value);
    partial void OncustoChanged();
    #endregion
		
		public produto()
		{
			this._itens = new EntitySet<iten>(new Action<iten>(this.attach_itens), new Action<iten>(this.detach_itens));
			this._fornecedore = default(EntityRef<fornecedore>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_produto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int cod_produto
		{
			get
			{
				return this._cod_produto;
			}
			set
			{
				if ((this._cod_produto != value))
				{
					this.Oncod_produtoChanging(value);
					this.SendPropertyChanging();
					this._cod_produto = value;
					this.SendPropertyChanged("cod_produto");
					this.Oncod_produtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_des_produto", DbType="VarChar(30)")]
		public string des_produto
		{
			get
			{
				return this._des_produto;
			}
			set
			{
				if ((this._des_produto != value))
				{
					this.Ondes_produtoChanging(value);
					this.SendPropertyChanging();
					this._des_produto = value;
					this.SendPropertyChanged("des_produto");
					this.Ondes_produtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ean", DbType="VarChar(20)")]
		public string ean
		{
			get
			{
				return this._ean;
			}
			set
			{
				if ((this._ean != value))
				{
					this.OneanChanging(value);
					this.SendPropertyChanging();
					this._ean = value;
					this.SendPropertyChanged("ean");
					this.OneanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_fornecedor", DbType="Int")]
		public System.Nullable<int> cod_fornecedor
		{
			get
			{
				return this._cod_fornecedor;
			}
			set
			{
				if ((this._cod_fornecedor != value))
				{
					if (this._fornecedore.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncod_fornecedorChanging(value);
					this.SendPropertyChanging();
					this._cod_fornecedor = value;
					this.SendPropertyChanged("cod_fornecedor");
					this.Oncod_fornecedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vl_produto", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> vl_produto
		{
			get
			{
				return this._vl_produto;
			}
			set
			{
				if ((this._vl_produto != value))
				{
					this.Onvl_produtoChanging(value);
					this.SendPropertyChanging();
					this._vl_produto = value;
					this.SendPropertyChanged("vl_produto");
					this.Onvl_produtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_est_produto", DbType="Real")]
		public System.Nullable<float> est_produto
		{
			get
			{
				return this._est_produto;
			}
			set
			{
				if ((this._est_produto != value))
				{
					this.Onest_produtoChanging(value);
					this.SendPropertyChanging();
					this._est_produto = value;
					this.SendPropertyChanged("est_produto");
					this.Onest_produtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_un_medida", DbType="NChar(10)")]
		public string un_medida
		{
			get
			{
				return this._un_medida;
			}
			set
			{
				if ((this._un_medida != value))
				{
					this.Onun_medidaChanging(value);
					this.SendPropertyChanging();
					this._un_medida = value;
					this.SendPropertyChanged("un_medida");
					this.Onun_medidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desc_reduzida", DbType="VarChar(30)")]
		public string desc_reduzida
		{
			get
			{
				return this._desc_reduzida;
			}
			set
			{
				if ((this._desc_reduzida != value))
				{
					this.Ondesc_reduzidaChanging(value);
					this.SendPropertyChanging();
					this._desc_reduzida = value;
					this.SendPropertyChanged("desc_reduzida");
					this.Ondesc_reduzidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_margem", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> margem
		{
			get
			{
				return this._margem;
			}
			set
			{
				if ((this._margem != value))
				{
					this.OnmargemChanging(value);
					this.SendPropertyChanging();
					this._margem = value;
					this.SendPropertyChanged("margem");
					this.OnmargemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_custo", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> custo
		{
			get
			{
				return this._custo;
			}
			set
			{
				if ((this._custo != value))
				{
					this.OncustoChanging(value);
					this.SendPropertyChanging();
					this._custo = value;
					this.SendPropertyChanged("custo");
					this.OncustoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="produto_iten", Storage="_itens", ThisKey="cod_produto", OtherKey="cod_produto")]
		public EntitySet<iten> itens
		{
			get
			{
				return this._itens;
			}
			set
			{
				this._itens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="fornecedore_produto", Storage="_fornecedore", ThisKey="cod_fornecedor", OtherKey="cod_fornecedor", IsForeignKey=true)]
		public fornecedore fornecedore
		{
			get
			{
				return this._fornecedore.Entity;
			}
			set
			{
				fornecedore previousValue = this._fornecedore.Entity;
				if (((previousValue != value) 
							|| (this._fornecedore.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._fornecedore.Entity = null;
						previousValue.produtos.Remove(this);
					}
					this._fornecedore.Entity = value;
					if ((value != null))
					{
						value.produtos.Add(this);
						this._cod_fornecedor = value.cod_fornecedor;
					}
					else
					{
						this._cod_fornecedor = default(Nullable<int>);
					}
					this.SendPropertyChanged("fornecedore");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_itens(iten entity)
		{
			this.SendPropertyChanging();
			entity.produto = this;
		}
		
		private void detach_itens(iten entity)
		{
			this.SendPropertyChanging();
			entity.produto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.usuarios")]
	public partial class usuario
	{
		
		private int _usu_codigo;
		
		private string _usu_nome;
		
		private string _usu_senha;
		
		public usuario()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_codigo", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int usu_codigo
		{
			get
			{
				return this._usu_codigo;
			}
			set
			{
				if ((this._usu_codigo != value))
				{
					this._usu_codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_nome", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string usu_nome
		{
			get
			{
				return this._usu_nome;
			}
			set
			{
				if ((this._usu_nome != value))
				{
					this._usu_nome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_senha", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string usu_senha
		{
			get
			{
				return this._usu_senha;
			}
			set
			{
				if ((this._usu_senha != value))
				{
					this._usu_senha = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vendas")]
	public partial class venda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cod_venda;
		
		private System.Nullable<System.DateTime> _dtvenda;
		
		private System.Nullable<int> _cod_cliente;
		
		private EntitySet<iten> _itens;
		
		private EntityRef<cliente> _cliente;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncod_vendaChanging(int value);
    partial void Oncod_vendaChanged();
    partial void OndtvendaChanging(System.Nullable<System.DateTime> value);
    partial void OndtvendaChanged();
    partial void Oncod_clienteChanging(System.Nullable<int> value);
    partial void Oncod_clienteChanged();
    #endregion
		
		public venda()
		{
			this._itens = new EntitySet<iten>(new Action<iten>(this.attach_itens), new Action<iten>(this.detach_itens));
			this._cliente = default(EntityRef<cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_venda", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int cod_venda
		{
			get
			{
				return this._cod_venda;
			}
			set
			{
				if ((this._cod_venda != value))
				{
					this.Oncod_vendaChanging(value);
					this.SendPropertyChanging();
					this._cod_venda = value;
					this.SendPropertyChanged("cod_venda");
					this.Oncod_vendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtvenda", DbType="Date")]
		public System.Nullable<System.DateTime> dtvenda
		{
			get
			{
				return this._dtvenda;
			}
			set
			{
				if ((this._dtvenda != value))
				{
					this.OndtvendaChanging(value);
					this.SendPropertyChanging();
					this._dtvenda = value;
					this.SendPropertyChanged("dtvenda");
					this.OndtvendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_cliente", DbType="Int")]
		public System.Nullable<int> cod_cliente
		{
			get
			{
				return this._cod_cliente;
			}
			set
			{
				if ((this._cod_cliente != value))
				{
					if (this._cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncod_clienteChanging(value);
					this.SendPropertyChanging();
					this._cod_cliente = value;
					this.SendPropertyChanged("cod_cliente");
					this.Oncod_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="venda_iten", Storage="_itens", ThisKey="cod_venda", OtherKey="cod_venda")]
		public EntitySet<iten> itens
		{
			get
			{
				return this._itens;
			}
			set
			{
				this._itens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_venda", Storage="_cliente", ThisKey="cod_cliente", OtherKey="cod_cliente", IsForeignKey=true)]
		public cliente cliente
		{
			get
			{
				return this._cliente.Entity;
			}
			set
			{
				cliente previousValue = this._cliente.Entity;
				if (((previousValue != value) 
							|| (this._cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._cliente.Entity = null;
						previousValue.vendas.Remove(this);
					}
					this._cliente.Entity = value;
					if ((value != null))
					{
						value.vendas.Add(this);
						this._cod_cliente = value.cod_cliente;
					}
					else
					{
						this._cod_cliente = default(Nullable<int>);
					}
					this.SendPropertyChanged("cliente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_itens(iten entity)
		{
			this.SendPropertyChanging();
			entity.venda = this;
		}
		
		private void detach_itens(iten entity)
		{
			this.SendPropertyChanging();
			entity.venda = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cidades")]
	public partial class cidade
	{
		
		private int _cid_codigo;
		
		private string _cid_nome;
		
		private string _cid_uf;
		
		public cidade()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cid_codigo", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int cid_codigo
		{
			get
			{
				return this._cid_codigo;
			}
			set
			{
				if ((this._cid_codigo != value))
				{
					this._cid_codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cid_nome", DbType="NVarChar(50)")]
		public string cid_nome
		{
			get
			{
				return this._cid_nome;
			}
			set
			{
				if ((this._cid_nome != value))
				{
					this._cid_nome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cid_uf", DbType="NVarChar(50)")]
		public string cid_uf
		{
			get
			{
				return this._cid_uf;
			}
			set
			{
				if ((this._cid_uf != value))
				{
					this._cid_uf = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
